development:
    adapter: sqlite3
    database: db/wmpapp_dev.sqlite3
    pool: 5
    timeout: 5000


production:
  adapter: postgresql
  database: wmapp_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: sqlite3
  database: db/wmapp_test.sqlite3
  pool: 5
  timeout: 5000
